### PR TITLE
update bitcoind version; bump version to 0.7.0

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @RCasatta this updates the bitcoind dep, uses `anyhow::Error` in a few places, and adds a new feature for Elements 22.

I can't run downloaded binaries on my system but I did confirm that you _can_ download the new 22.1.1 binary.

**Comment by RCasatta** [comment]
Thanks!
There are errors in ci: the format one is trivial the other is not.
MSRV at the moment is 1.57.0 because `ureq` updated without preserving MSRV
bitcoind migrated to `minreq` because it looks the rust-bitcoin community is converging to that because has a more strict MSRV policy, however, even with #7 with https they are not granting 1.48 https://github.com/neonmoe/minreq/#minimum-supported-rust-version-msrv so the MSRV is still 1.57.0
bitcoind is granting a lower MSRV without download features, I'll prepare that MR later today

**Comment by RCasatta** [comment]
Also it looks the binary download for the added version 22.1.1 is not working at the moment, I'll investigate later today.

UPDATE: the sha256 file was missing, fix https://github.com/RCasatta/elementsd/commit/af8370604757e63c968d7fd55f6a0c8ae6c8009a

**Comment by apoelstra** [comment]
Oof, sorry, I forgot to commit the sha2sums file! Thanks for finding it.

**Comment by RCasatta** [comment]
I prepared #8, contains your commit and rebase on top of #7

**Comment by apoelstra** [comment]
Thanks! I'll review this shortly.

**Pull request closed without merging**
