### PR TITLE
bump bitcoind dependency and version

### PR DESCRIPTION
**Pull request by apoelstra**
Needed to update rust-elements.

### CODE REVIEW

**Comment by apoelstra** [comment]
I did not look at whether the latest version of bitcoind supports any new bitcoind versions or features; I just bumped the dep and checked whether it worked.

In fact we could do a ranged dependency, changing from 0.34 to `">=0.34.0, <=0.36.0"` ... and probably even lower the range below 0.34.0. But I don't think there's really any value in doing that. It would let people use the same `elementsd` version across multiple versions of bitcoin but what does that gain us?

**Comment by RCasatta** [comment]
Sorry for the delay, I was in PTO...

ACK 328e1f6df85cd6c34d7dcd3b314b6c80463f1582

> In fact we could do a ranged dependency, changing from 0.34 to ">=0.34.0, <=0.36.0" ... and probably even lower the range below 0.34.0. But I don't think there's really any value in doing that. It would let people use the same elementsd version across multiple versions of bitcoin but what does that gain us?

Having range dep could help in avoiding multiple versions in some cases? but I think it can introduce some maintenance cost (should multiple version being tested than?) So, yeah, I don't think it's worth it.

**Comment by RCasatta** [comment]
> Sorry for the delay, I was in PTO...

BTW I now  added @LeoComandini as mantainer, I forgot this one was without a second mantainer

**Comment by RCasatta** [comment]
And also released on crate https://crates.io/crates/elementsd

**Pull request merged**
